// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoApi.Models;

#nullable disable

namespace proyectoApi.Migrations
{
    [DbContext(typeof(PruebaContext))]
    [Migration("20220908145152_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("proyectoApi.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado1")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Estado");

                    b.HasKey("Id");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("proyectoApi.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Foto")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pasaporte")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("proyectoApi.Models.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Solicitud", (string)null);
                });

            modelBuilder.Entity("proyectoApi.Models.Solicitud", b =>
                {
                    b.HasOne("proyectoApi.Models.Estado", "Estado")
                        .WithMany("Solicituds")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK__Solicitud__Estad__164452B1");

                    b.HasOne("proyectoApi.Models.Persona", "Persona")
                        .WithMany("Solicituds")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK__Solicitud__Perso__15502E78");

                    b.Navigation("Estado");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("proyectoApi.Models.Estado", b =>
                {
                    b.Navigation("Solicituds");
                });

            modelBuilder.Entity("proyectoApi.Models.Persona", b =>
                {
                    b.Navigation("Solicituds");
                });
#pragma warning restore 612, 618
        }
    }
}
